### ISSUE TITLE
No data in response.

### ISSUE THREAD

**Issue by norganna** [michelin/snowflake-grafana-datasource#1]
Hi,

I installed this on a test grafana instance at work and hooked it up to snowflake.

I can see the query going out to snowflake and returning results, but there's no data being plotted on the graph.

I've attached the panel JSON and the query JSON from the query inspector.

[panel.txt](https://github.com/michelin/snowflake-grafana-datasource/files/6537859/panel.txt)
[query.txt](https://github.com/michelin/snowflake-grafana-datasource/files/6537860/query.txt)

**Comment by norganna** [comment]
![image](https://user-images.githubusercontent.com/694366/119468732-0f9cc180-bd8a-11eb-9b26-4f9be48fb229.png)

**Comment by devnied** [comment]
Hi, 

Can you please give me your Grafana version ?
Do you see the data in the Query inspector panel (In the Data tab) ?

**Comment by norganna** [comment]
It's current development version `Grafana v8.1.0-pre (9b518669dd)` from git clone.

The data tab says there's no data.
![image](https://user-images.githubusercontent.com/694366/119496990-649b0080-bda7-11eb-95bd-49930e19eafc.png)

However the query tab says there is:
![image](https://user-images.githubusercontent.com/694366/119496918-4fbe6d00-bda7-11eb-865f-a0509ce8cc22.png)

**Comment by devnied** [comment]
I have not yet tested with the current development version of Grafana.
Can you try with the latest stable version if you have the same issue ?

**Comment by norganna** [comment]
The same query works fine in Grafana v7.5.7 (91de51771c)

Interestingly the response looks different in this version:
![image](https://user-images.githubusercontent.com/694366/119582719-68ab3a80-be08-11eb-86b2-654eee2d1967.png)

**Comment by devnied** [comment]
I have tried yesterday with the latest nightly build without issues https://grafana.com/grafana/download/8.1.0-23487pre.
The UI is not the same as the one in your capture https://github.com/michelin/snowflake-grafana-datasource/issues/1#issuecomment-847681918, maybe you have an issue with the frontend when you built it from source.

**Comment by norganna** [comment]
If that's the case, that would be really embarrassing. I'll check it out.

**Comment by norganna** [comment]
That's what was wrong, I wasn't putting the public files into the correct directory in my docker container, so it was using the old interface instead of the new one.

When I put it in the correct directory it all works fine.

How awkward :(
