### ISSUE TITLE
Error 260012: client configuration failed

### ISSUE THREAD

**Issue by Inmoide8** [michelin/snowflake-grafana-datasource#103]
Hi, when I installed version 1.8.0 and entered the credentials this error appeared:

"260012: client configuration failed: error while searching for client config in directory: /home/grafana, err: stat /home/grafana/sf_client_config.json: permission denied"

I have searched the sf_client_config.json file but I haven't found it.
I did this installation on another grafana and the result was ok, also here the sf_client_config.json doesn't exist either but the plugin is working correctly..could you help me with this case please?

Thanks you so much

**Comment by devnied** [comment]
Hello,
By default the snowflake sdk try to check if a default configuration file exist [see](https://github.com/snowflakedb/gosnowflake/blob/45b3d453b0a8fee8130da117420424483fe43cea/client_configuration.go#L59). 
It seems there might be an issue with the permissions on the parent directory /home/grafana. For this plugin, the file sf_client_config.json is not required and should not exist, so its absence is normal. Please check and correct the permissions if needed.
