### ISSUE TITLE
Time-series unable to add "Labels to fields" transformation

### ISSUE THREAD

**Issue by heanlan** [michelin/snowflake-grafana-datasource#15]
I'm trying to add a "Labels to fields" transformation to the time-series panel, so that it will show the "group by" column instead of aggregated metric column in the legend. But it tells me there is no available label.

Executed query:
```sql
SELECT timeField as time,
CONCAT(source, '->', destination) as pair,
AVG(throughput)
FROM table
WHERE $__timeFilter(time)
GROUP BY time, pair
HAVING AVG(throughput) > 0
ORDER BY time
```

Expected(snowflake plugin by Grafana-lab):
![image](https://user-images.githubusercontent.com/80798942/189734794-717c34de-d484-452e-ad22-81b3e339ccf5.png)

Actual graph-view:
![image](https://user-images.githubusercontent.com/80798942/189734875-a2816b7b-3628-4616-b4d4-e5c34213d934.png)

Actual table-view:
![image](https://user-images.githubusercontent.com/80798942/189735441-fbd268e6-c322-4faa-8480-836d9ac0bfb9.png)

Grafana: v8.3.3

**Comment by kranthikirang** [comment]
I think I am also looking for the same behavior. When I use mysql for similar query

`SELECT $__timeGroup(DATETIME,$__interval) as Time, HOST as metric, (max(USED/1024*1024)/max(TOTAL/1024*1024)*100) AS used_percent
FROM SERVER_MEMORY  WHERE $__timeFilter(DATETIMEUTC,$__interval) AND SERVICE='service1'
GROUP BY 1,2
ORDER BY  1`

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/18152400/191349536-0a1c62df-fece-4a8a-953e-4da5c15e81ca.png">

Where as using snowflake plugin

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/18152400/191349600-1f497736-60d5-4d24-8a88-74aab818a954.png">

Expected result: We should see a separate column for each HOST(metric) in a given time series
