### ISSUE TITLE
GROUP BY 2 columns results column name with field name + label

### ISSUE THREAD

**Issue by kranthikirang** [michelin/snowflake-grafana-datasource#23]
Grafana Version: 9.1.1
Plugin version: v1.2.0

Executed Query:

SELECT $__timeGroup(DATETIME,$__interval) as Time, HOST as metric, (max(USED/1024*1024)/max(TOTAL/1024*1024)*100) AS used_percent FROM SERVER_MEMORY WHERE $__timeFilter(DATETIMEUTC,$__interval) GROUP BY 1,2 ORDER BY 1

Everything looks good except data comes like below

<img width="435" alt="image" src="https://user-images.githubusercontent.com/18152400/192316377-df34bf0b-b69d-47a7-8ac6-2e982f61bb28.png">

<img width="1504" alt="image" src="https://user-images.githubusercontent.com/18152400/192316458-fb059e4c-3251-4678-ad0f-ba5c6df4938c.png">

USED_PERCENT is appended with HOST (included with a space). Using flowchart plugin which grabs the field name always displays as "USED_PERCENT" for all the hosts

<img width="380" alt="image" src="https://user-images.githubusercontent.com/18152400/192316722-28eecdb8-e555-4402-9a00-a71fd4c0a229.png">

Expected Behavior:

We should see labels as field names i.e., each HOST should displayed as column name instead of "USED_PERCENT {HOST}" it should be just "HOST"

**Comment by heanlan** [comment]
I'm not a maintainer. And I haven't try the flowchart plugin before. Not sure if it helps.

Have you ever tried to add the transformation "Labels to fields" like what I described in #15 , what you got seems very like something before applying the transformation.

![image](https://user-images.githubusercontent.com/80798942/193353932-b3ca5195-8148-485f-9227-5e2fda4e03b6.png)

**Comment by kranthikirang** [comment]
I have tried transformation "labels to fields" and it almost worked but flowchart plugin shows "Apply to Metrics" as "undefined" and Apply to columns shows proper names but saving the dashboard never works. Since after transformation Ref Id will not be there :(

**Comment by kranthikirang** [comment]
https://github.com/michelin/snowflake-grafana-datasource/pull/28 - can someone review this please?
