### ISSUE TITLE
Error when adding "LIMIT" keyword to time-series

### ISSUE THREAD

**Issue by heanlan** [michelin/snowflake-grafana-datasource#26]
When I try to add "LIMIT" keyword to queries of time-series panel, it always reports error "001003 (42000): SQL compilation error: syntax error line 7 at position 9 unexpected 'LIMIT'."

Query:
```sql
SELECT TIME_SLICE(TO_TIMESTAMP(CONVERT_TIMEZONE('UTC', flowEndSeconds)), 60, 'SECOND', 'START') as time, 
count(*) as count,
sourceNodeName
FROM flows
WHERE $__timeFilter(time)
GROUP BY time, sourceNodeName
ORDER BY time
LIMIT 10
```

Error msg:
<img width="795" alt="image" src="https://user-images.githubusercontent.com/80798942/193354386-e2577a3c-ff5c-42aa-a494-0c1cf6624cfa.png">

Query config:
![image](https://user-images.githubusercontent.com/80798942/193354584-08d14cba-8e15-4dee-8646-e9dfe4ab46e2.png)

From the error message we can tell it applies both the default max data points 1526 and the limit 10 defined in the query, which leads to error.

When looking at the code, I have trouble to understand these line:
https://github.com/michelin/snowflake-grafana-datasource/blob/7d3541024c6aaa0c90c2c15e77b1e48773eae273/pkg/query.go#L215-L216
It will automatically append "LIMIT maxDataPoints" to the end of the query, which always cause error. 

The purpose for me to add "LIMIT 10" to the query is to limit the number of series it returns. While the [definition](https://grafana.com/docs/grafana/latest/panels/query-options/) of maxDataPoints is "sets the maximum numbers of data points for EACH series returned." I don't think the code is correctly supporting maxDataPoints.

**Comment by devnied** [comment]
Thanks for the report.

The goal of the 'LIMIT maxDataPoints' is to avoid to load too many data from Snowflake and restrict the amount of data to the width of the panel.

But the code you highlight have a conditional issue is will fix this.

As a workaround you can add comment at the end of your query.
```sql
SELECT TIME_SLICE(TO_TIMESTAMP(CONVERT_TIMEZONE('UTC', flowEndSeconds)), 60, 'SECOND', 'START') as time, 
count(*) as count,
sourceNodeName
FROM flows
WHERE $__timeFilter(time)
GROUP BY time, sourceNodeName
ORDER BY time
LIMIT 10 //
```

**Comment by heanlan** [comment]
Thanks for the quick fix. When can we expect the 1.2.1 release?
