### ISSUE TITLE
Dashboard variables and annotations lack ability to enter a Query

### ISSUE THREAD

**Issue by mshirman** [michelin/snowflake-grafana-datasource#3]
Both dashboard variables and the annotations are missing the option to add a Query. Unable to add variables and annotations to the dashboards. Is this something meant to be supported by the plugin?

**Comment by staier** [comment]
Yes, please .
For example i am trying to filter stats by account or warehouse.
now i have to  maintain the list  of accounts ,  but it is impossible to maintain a list  of warehouses as it  depends on account.

**Comment by inacionery** [comment]
I sent a proposal here https://github.com/michelin/snowflake-grafana-datasource/pull/5
