### ISSUE TITLE
The private key of base64 URL encoded pkcs8

### ISSUE THREAD

**Issue by mingtao13595** [michelin/snowflake-grafana-datasource#38]
Thanks for this increidible plugin for visualizing snowflake data on Grafana.
I've successfully installed and tested my snowflake acount  with multi-factor authentication (i.e. MFA).
But it needs Approval each time for testing SQL and refreshing visualizations, which is inconveniently for me.
Since Key Pair Authentication will be more silently and the keys obtained by the way below works well for SnowSQL.
https://docs.snowflake.com/en/user-guide/key-pair-auth.html
However, neither manually converting "+" to "-" and "\" to "_" and remove "\n" as told,
nor the methods given in readme, it gives the same error as follow.
The  private key is generated as RSA2048, is it means impossible to conver rsa2048 to base64 URL ?
In addition, the private key was generated as follow.
$ openssl genrsa 2048 | openssl pkcs8 -topk8 -inform PEM -out rsa_key.p8
Thank you in advance!
> egrep -v '^(-----BEGIN PRIVATE KEY|-----END PRIVATE KEY)' rsa_key.p8 | tr -d '\n' | sed 's/+/-/g; s/\//_/g' > rsa_key_urlbase64.p8
![image](https://user-images.githubusercontent.com/9034078/214461206-a962bb7b-7fd7-4d4b-ae87-cf6e0419109e.png)

**Comment by mingtao13595** [comment]
Generating private key again as the method SNOWFLAKE told as follow. 
It works well! sorry for this issue. please close it. Thank you!
$ openssl genrsa 2048 | openssl pkcs8 -topk8 -inform PEM -out rsa_key.p8 -nocrypt

**Comment by devnied** [comment]
Thanks for your feedback.

**Comment by Ten0** [comment]
It's unclear to me how to specify the private key as base64 URL. I don't see where the documentation about how to convert to URL is.

Using the proposed command above (which I don't know where it comes from) gives:
```
sed: -e expression #1, char 14: unknown option to `s'
```
and it's unclear what the intent is.

What does it mean to `convert "" to "_"`?

Everything i tried gives:
```
Connection issue : 260010: Error decoding private key using PKCS8.
```
