### ISSUE TITLE
Can not update query in query editor when using v1.6.1

### ISSUE THREAD

**Issue by tiantangkuohai** [michelin/snowflake-grafana-datasource#76]

**Comment by tiantangkuohai** [comment]
Any updates on this?

**Comment by jcarlosmayo** [comment]
Same issue here. The sample query that is provided by default never gets updated and errors out. The only workaround we have found so far is to edit the query in the JSON payload that gets sent to Snowflake.

**Comment by jcarlosmayo** [comment]
Following up on my previous comment. We got it to work. The problem for us seems to have been the version of Grafana we were running. We had deployed the image `grafana/grafana-oss:9.5.20-ubuntu` and updating to the latest available - `grafana-oss:11.1.4-ubuntu` - fixed the problem.

**Comment by tiantangkuohai** [comment]
Thank you @jcarlosmayo . I will update my Grafana to v11.1.
