### ISSUE TITLE
Will this work with Grafana community edition (not cloud, not enterprise)

### ISSUE THREAD

**Issue by Alonzzzo2** [michelin/snowflake-grafana-datasource#81]
Hi,
Sorry for creating an 'issue' for this question, didn't know how else to post an inquiry
We have Grafana community edition, when trying to install a connection to snowflake (a different plugin) we got a message saying:
"No valid Grafana Enterprise license detected."
Will I be able to install this plugin?
Thanks!

**Comment by devnied** [comment]
Yes, you can follow the installation guide of this plugin: https://github.com/michelin/snowflake-grafana-datasource?tab=readme-ov-file#set-up-the-snowflake-data-source
