### ISSUE TITLE
Snowflake query timeout 

### ISSUE THREAD

**Issue by nparmarviasat** [michelin/snowflake-grafana-datasource#83]
Hi,
My query timing out here is message
**"Error message
request handler error: failed to query data: Failed to query data: rpc error: code = DeadlineExceeded desc = context deadline exceeded"**

and i looking to configure timeout parameter for this , i don't have any-options ( i see in UI)

There is should be way configure the timeout

**Comment by devnied** [comment]
in the `extra options` field you can add all connection parameters https://pkg.go.dev/github.com/snowflakedb/gosnowflake#hdr-Connection_Parameters like `requestTimeout=0`
