### ISSUE TITLE
snowflake connection and SQL compilation error 

### ISSUE THREAD

**Issue by waqas-saeed** [michelin/snowflake-grafana-datasource#94]
I've noticed a problem where my sql isn't able to return data and I get this error:

`001003 (42000): SQL compilation error: syntax error line 6 at position 0 unexpected 'WHERE'.`

When I looked into the connections and clicked on `save & test`

first time I get this message

`Data source is working`

but if I click on it again I get this error message

`Validation query error : sql: database is closed`

I ran the exact same sql in snowflake console it works fine with no error and returns result.

With `snowflake-grafana-datasource version Release v1.5.0` everything works as expected. I can test my connection multiple times and don't get any error and my sql also works perfectly. 

Environment details where I have encountered connection and sql issue. 
Grafana v10.0.1 (5a30620b85)
snowflake-grafana-datasource version Release v1.8.0

**Comment by devnied** [comment]
I encountered the same issue after an upgrade, but restarting Grafana resolved it.

**Comment by negordyh** [comment]
Hopefully Michelin can fix this issue soon. We have to restart Grafana when experience this. It's inconvenient.
![image](https://github.com/user-attachments/assets/4caf4732-4142-4fb9-8508-5d6096567dfb)

**Comment by devnied** [comment]
@negordyh Which version of Grafana do you use?
